config/routes.rb
Rails.application.routes.draw do
  resources :polls
  resources :answers, only: [:create]

  devise_for :users

  root 'polls#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :choice

  validate :user_has_not_answered
  def user_has_not_answered
    errors.add(:user, 'has already answered') if user.answered_for? choice.poll
  end
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :poll
  has_many :users, through: :answers
  has_many :answers, dependent: :destroy

  validates_presence_of :title
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :choices, dependent: :destroy
  has_many :answers, through: :choices

  validates_presence_of :topic, :description, :choices

  accepts_nested_attributes_for :choices, :reject_if => :all_blank, :allow_destroy => true

  def normalized_answers_for(choice)
    answers_summary == 0 ? 0 : (choice.answers.count.to_f / answers_summary) * 100
  end

  def answers_summary
    choices.inject(0) {|summary, choice| summary + choice.answers.count}
  end

  def self.active
    where("created_at <= ? AND expires >= ? AND active = ?", Time.now, Time.now, true)
  end

  def self.inactive
    where("created_at <= ? AND expires >= ? AND active = ?", Time.now, Time.now, false)
  end

  def self.expired
    where("created_at <= ? AND expires <= ?", Time.now, Time.now)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  has_many :choices, through: :answers
  has_and_belongs_to_many :polls

  validates_presence_of :email
  validates_uniqueness_of :email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def answered_for?(poll)
    answers.any? {|v| v.choice.poll == poll}
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    choice = Choice.find(params[:choice][:id])
    answer = Answer.create user: current_user, choice: choice
    if answer.valid?
      redirect_to poll_path choice.poll, hide_already_answered: true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.active
    @scope = params[:scope]
    @polls = Poll.all.expired if @scope == 'expired'
    @polls = Poll.all.active if @scope == 'active'
    @polls = Poll.all.inactive if @scope == 'inactive'
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.includes(:choices).find_by_id(params[:id])
    @hide_already_answered = params[:hide_already_answered]
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:id, :topic, :description, :expires, :active, :created_at, :updated_at, choices_attributes: [:id, :title, :description, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
  def visualize_answers_for(choice)
    content_tag :div, class: 'progress' do
      content_tag :div, class: 'progress-bar',
                  style: "width: #{choice.poll.normalized_answers_for(choice)}%" do
        "#{choice.answers.count}"
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consensus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/_answer_form.html.slim
= form_tag answers_path, method: :post, id: 'answer_form' do
  = hidden_field_tag 'poll[id]', @poll.id

  = render partial: 'choice', collection: @poll.choices, as: :choice
  p
    b Total votes: &nbsp;
    = @poll.answers_summary

  - if current_user.answered_for?(@poll) && !@hide_already_answered
    .alert.alert-warning You have already answered!
  - elsif (@scope != 'expired')
    = submit_tag 'Answer', class: 'btn btn-primary'
  end
end

app/views/polls/_choice.html.slim
.form-group
  = content_tag(:label) do
    - unless current_user.answered_for?(@poll)
      = radio_button_tag 'choice[id]', choice.id
    end
    = choice.title
    .small = choice.description
  end
  = visualize_answers_for choice

app/views/polls/_choice_fields.html.slim
.well.nested-fields
  .form-inline
    = f.label 'Title', class: 'col-sm-2 control-label'
    = f.text_field :title, class: 'form-control'
  .form-inline
    = f.label 'Description', class: 'col-sm-2 control-label'
    = f.text_field :description, class: 'form-control'
    = link_to_remove_association "Delete", f, class: 'btn btn-danger navbar-right'

app/views/polls/_form.html.slim
= form_for @poll, html: {class: 'form-horizontal'} do |f|
  - if @poll.errors.any?
    #error_explanation
      .alert.alert-danger
        h2 = "#{pluralize(@poll.errors.count, "error")} prohibited this poll from being saved:"
        ul
          - @poll.errors.full_messages.each do |message|
            li = message

  .form-group
    = f.label :topic, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :topic, class: 'form-control', required: true
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, class: 'form-control', required: true
  .form-group
    .form-inline
      = f.label :expires, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.datetime_select :expires, {:minute_step => 15, :default => Time.now+2.hours, :order => [:day, :month, :year]}, {:class => 'form-control'}
  .form-group
    .form-inline
      =f.label :active, class: 'col-sm-2 control-label'
      .col-sm-10.checkbox
        = f.check_box :active, {:checked => true}

  .form-group
    = f.label 'Choices', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.fields_for :choices do |choices_form|
        == render 'choice_fields', f: choices_form
      end
      .links = link_to_add_association 'Add Choice', f, :choices, class: 'btn btn-default'

  .action = f.submit nil, :class => 'btn btn-primary'
br

app/views/polls/edit.html.slim
h1 Editing poll

== render 'form'

.btn-group
  = link_to 'Show', @poll, :class => 'btn btn-primary'
  = link_to 'Back', polls_path, :class => 'btn btn-default'

app/views/polls/index.html.slim
ul.nav.navbar-nav.navbar-right
  li = link_to 'New Poll', new_poll_path
  - if (@scope == 'active' || @scope == nil)
    li = link_to 'Inactive Polls', polls_path(:scope => 'inactive')
    li = link_to 'Expired Polls', polls_path(:scope => 'expired')
  - elsif (@scope == 'inactive')
    li = link_to 'Active Polls', polls_path(:scope => 'active')
    li = link_to 'Expired Polls', polls_path(:scope => 'expired')
  - elsif (@scope == 'expired')
    li = link_to 'Active Polls', polls_path(:scope => 'active')
    li = link_to 'Inactive Polls', polls_path(:scope => 'inactive')
  li = link_to current_user.email, destroy_user_session_path, :method => :delete
h1 Listing polls

p#notice
  span.label.label-info = notice

table class='table table-hover'
  thead
    tr
      th Topic
      th Description
      th Expires
      th Voted
      th
      - if (@scope != 'expired')
        th
      th

  tbody
    - @polls.each do |poll|
      tr
        td = poll.topic
        td = poll.description
        td = poll.expires
        td
          .badge = poll.answers_summary
        - if (@scope == 'active')
          td = link_to 'Participate', poll, class: 'btn btn-default'
        - else
          td = link_to 'Show', poll, class: 'btn btn-default'
        - if (@scope != 'expired')
          td = link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default'
        td = link_to 'Delete', poll, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger'

app/views/polls/new.html.slim
h1 Create a new poll

== render 'form'

= link_to 'Back', polls_path, class: 'btn btn-default'

app/views/polls/show.html.slim
p#notice
  span.label.label-info = notice

.well
  .row
    .col-sm-2
      h2 = @poll.topic
  .row
    .col-sm-2
      strong Description
    = @poll.description
  .row
    .col-sm-2
      strong Expires
    = @poll.expires
  .row
    .col-sm-2
      strong Active
    = @poll.active
  .row
    .col-sm-2
      strong Created at
    = @poll.created_at
  .row
    .col-sm-2
      strong Updated at
    = @poll.updated_at

== render 'answer_form'

.btn-group
  = link_to 'Edit', edit_poll_path(@poll), :class => 'btn btn-primary'
  = link_to 'Back', polls_path, :class => 'btn btn-default'